CREATE TABLE USERS (
    USER_ID      VARCHAR2(20),
    EMAIL        VARCHAR2(200)  NOT NULL,
    PASSWORD     VARCHAR2(255)  NOT NULL,
    NICKNAME     VARCHAR2(30)   NOT NULL,
    PHONE        VARCHAR2(20),
    PROFILE_IMG  VARCHAR2(500),
    BIRTHDAY     DATE,
    IS_DELETED   NUMBER(1,0)    DEFAULT 0 NOT NULL,
    MEDAL_GRADE  VARCHAR2(10),
    PRIMARY KEY (USER_ID),
    UNIQUE (EMAIL),
    UNIQUE (NICKNAME)
);
CREATE TABLE CATEGORY_L (
    CATEGORYL_ID NUMBER(11,0),
    NAME         VARCHAR2(50)  NOT NULL,
    TYPE         VARCHAR2(20)  NOT NULL,
    PRIMARY KEY (CATEGORYL_ID)
);
CREATE TABLE CATEGORY_M (
    CATEGORYM_ID NUMBER(11,0),
    CATEGORYL_ID NUMBER(11,0)  NOT NULL,
    NAME         VARCHAR2(50)  NOT NULL,
    TYPE         VARCHAR2(20)  NOT NULL,
    PRIMARY KEY (CATEGORYM_ID),
    CONSTRAINT FK_CATM_CATL FOREIGN KEY (CATEGORYL_ID) REFERENCES CATEGORY_L (CATEGORYL_ID)
);
CREATE TABLE RECIPE (
    RECIPE_ID   NUMBER(20,0),
    USER_ID     VARCHAR2(20)   NOT NULL,
    CATEGORY_ID NUMBER(11,0)   NOT NULL,
    TITLE       VARCHAR2(200)  NOT NULL,
    THUMBNAIL   VARCHAR2(500),
    DESCRIPTION CLOB,
    SERVINGS    NUMBER(5,0)    NOT NULL,
    COOK_TIME   NUMBER(5,0)    NOT NULL,
    DIFFICULTY  NUMBER(1,0)    NOT NULL,
    VIEW_COUNT  NUMBER(11,0)   DEFAULT 0 NOT NULL,
    AVG_RATING  NUMBER(3,1),
    IS_DELETED  NUMBER(1,0)    DEFAULT 0 NOT NULL,
    CREATED_AT  DATE           DEFAULT SYSDATE NOT NULL,
    LINK        VARCHAR2(500),
    CONSTRAINT CK_RECIPE_DIFF CHECK (DIFFICULTY IN (1,2,3)),
    PRIMARY KEY (RECIPE_ID),
    CONSTRAINT FK_RECIPE_USER     FOREIGN KEY (USER_ID)     REFERENCES USERS (USER_ID),
    CONSTRAINT FK_RECIPE_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY_M (CATEGORYM_ID)
);
CREATE TABLE REVIEW (
    REVIEW_ID        NUMBER(20,0),
    USER_ID          VARCHAR2(20)  NOT NULL,
    RECIPE_ID        NUMBER(20,0)  NOT NULL,
    RATING           NUMBER(3,1),
    CONTENT          CLOB,
    PARENT_REVIEW_ID NUMBER(20,0),
    IS_DELETED       NUMBER(1,0)   DEFAULT 0 NOT NULL,
    CREATED_AT       DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_REVIEW_RATING CHECK (RATING IS NULL OR (RATING BETWEEN 1.0 AND 5.0)),
    PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_REVIEW_USER   FOREIGN KEY (USER_ID)          REFERENCES USERS (USER_ID),
    CONSTRAINT FK_REVIEW_RECIPE FOREIGN KEY (RECIPE_ID)        REFERENCES RECIPE (RECIPE_ID),
    CONSTRAINT FK_REVIEW_PARENT FOREIGN KEY (PARENT_REVIEW_ID) REFERENCES REVIEW (REVIEW_ID)
);
CREATE TABLE INGREDIENT (
    INGREDIENT_ID NUMBER(11,0),
    NAME          VARCHAR2(100) NOT NULL,
    UNIT          VARCHAR2(20),
    PRIMARY KEY (INGREDIENT_ID)
);
CREATE TABLE RECIPE_INGREDIENTS (
    RECIPE_INGR_ID NUMBER(20,0),
    INGREDIENT_ID  NUMBER(11,0) NOT NULL,
    RECIPE_ID      NUMBER(20,0) NOT NULL,
    AMOUNT         VARCHAR2(50) NOT NULL,
    PRIMARY KEY (RECIPE_INGR_ID),
    CONSTRAINT FK_RI_INGREDIENT FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT (INGREDIENT_ID),
    CONSTRAINT FK_RI_RECIPE     FOREIGN KEY (RECIPE_ID)     REFERENCES RECIPE (RECIPE_ID) ON DELETE CASCADE
);
CREATE TABLE RECIPE_STEP (
    STEP_ID   NUMBER(20,0),
    RECIPE_ID NUMBER(20,0) NOT NULL,
    STEP_NO   NUMBER(5,0)  NOT NULL,
    IMAGE_URL VARCHAR2(500),
    CONTENT   CLOB         NOT NULL,
    PRIMARY KEY (STEP_ID),
    CONSTRAINT FK_STEP_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (RECIPE_ID) ON DELETE CASCADE
);
CREATE TABLE RECOMMENDED_THEME (
    THEME_ID    NUMBER(11,0),
    USER_ID     VARCHAR2(20)   NOT NULL,
    TITLE       VARCHAR2(100)  NOT NULL,
    DESCRIPTION CLOB,
    THUMBNAIL   VARCHAR2(500),
    LINK_URL    VARCHAR2(500),
    IS_VISIBLE  NUMBER(1,0)    DEFAULT 1 NOT NULL,
    VIEW_COUNT  NUMBER(11,0)   DEFAULT 0 NOT NULL,
    CREATED_AT  DATE           DEFAULT SYSDATE NOT NULL,
    SUBTITLE    VARCHAR2(200),
    PRIMARY KEY (THEME_ID),
    CONSTRAINT FK_THEME_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);
CREATE TABLE RECIPE_LIKE (
    RECIPE_ID  NUMBER(20,0)  NOT NULL,
    USER_ID    VARCHAR2(20)  NOT NULL,
    CREATED_AT DATE          DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (RECIPE_ID, USER_ID),
    CONSTRAINT FK_LIKE_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (RECIPE_ID),
    CONSTRAINT FK_LIKE_USER   FOREIGN KEY (USER_ID)   REFERENCES USERS (USER_ID)
);
CREATE TABLE FAVORITE (
    FAVORITE_ID NUMBER(20,0),
    USER_ID     VARCHAR2(20)  NOT NULL,
    RECIPE_ID   NUMBER(20,0)  NOT NULL,
    CREATED_AT  DATE          DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (FAVORITE_ID),
    CONSTRAINT UQ_FAVORITE   UNIQUE (USER_ID, RECIPE_ID),
    CONSTRAINT FK_FAV_USER   FOREIGN KEY (USER_ID)   REFERENCES USERS (USER_ID),
    CONSTRAINT FK_FAV_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (RECIPE_ID)
);
CREATE TABLE THEME_RECIPE (
    THEME_RECIPE_ID NUMBER(20,0),
    THEME_ID        NUMBER(11,0)  NOT NULL,
    RECIPE_ID       NUMBER(20,0)  NOT NULL,
    SORT_ORDER      NUMBER(5,0),
    USER_ID         VARCHAR2(20),
    DESCRIPTION     VARCHAR2(1000),
    PRIMARY KEY (THEME_RECIPE_ID),
    CONSTRAINT UQ_THEME_RECIPE UNIQUE (THEME_ID, RECIPE_ID),
    CONSTRAINT FK_TR_THEME  FOREIGN KEY (THEME_ID)  REFERENCES RECOMMENDED_THEME (THEME_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TR_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (RECIPE_ID)
);
CREATE TABLE CHEF_INTRO (
    USER_ID    VARCHAR2(50)   NOT NULL,
    INTRO      VARCHAR2(1000),
    UPDATED_AT DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CHEF_INTRO      PRIMARY KEY (USER_ID),
    CONSTRAINT FK_CHEF_INTRO_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);
CREATE SEQUENCE SEQ_CATEGORY_L  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_M  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECIPE       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INGREDIENT   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECIPE_INGR  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECIPE_STEP  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_THEME        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FAVORITE     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_THEME_RECIPE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE RECOMMENDED_THEME_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_RECIPE_USER     ON RECIPE (USER_ID);
CREATE INDEX IDX_RECIPE_CATEGORY ON RECIPE (CATEGORY_ID);
CREATE INDEX IDX_RECIPE_CREATED  ON RECIPE (CREATED_AT DESC);
CREATE INDEX IDX_RECIPE_VIEWCNT  ON RECIPE (VIEW_COUNT DESC);
CREATE INDEX IDX_RECIPE_RATING   ON RECIPE (AVG_RATING DESC);
CREATE INDEX IDX_REVIEW_RECIPE   ON REVIEW (RECIPE_ID);
CREATE INDEX IDX_REVIEW_PARENT   ON REVIEW (PARENT_REVIEW_ID);
CREATE INDEX IDX_FAVORITE_USER   ON FAVORITE (USER_ID);
CREATE INDEX IDX_THEME_VISIBLE   ON RECOMMENDED_THEME (IS_VISIBLE, CREATED_AT DESC);
INSERT INTO USERS VALUES ('admin','admin@bggchef.com','admin1234','관리자','010-0000-0000',NULL,NULL,0,'골드');
INSERT INTO CATEGORY_L VALUES (1, '한식', 'CULTURE');
INSERT INTO CATEGORY_L VALUES (2, '양식', 'CULTURE');
INSERT INTO CATEGORY_L VALUES (3, '중식', 'CULTURE');
INSERT INTO CATEGORY_L VALUES (4, '일식', 'CULTURE');
INSERT INTO CATEGORY_L VALUES (5, '디저트', 'KIND');
INSERT INTO CATEGORY_L VALUES (6, '음료', 'KIND');
INSERT INTO CATEGORY_L VALUES (7, '분식', 'KIND');
INSERT INTO CATEGORY_M VALUES (1, 1, '찌개/국', 'KIND');
INSERT INTO CATEGORY_M VALUES (2, 1, '구이',    'KIND');
INSERT INTO CATEGORY_M VALUES (3, 1, '볶음',    'KIND');
INSERT INTO CATEGORY_M VALUES (4, 2, '파스타',  'KIND');
INSERT INTO CATEGORY_M VALUES (5, 2, '스테이크','KIND');
INSERT INTO CATEGORY_M VALUES (6, 3, '면류',    'KIND');
INSERT INTO CATEGORY_M VALUES (7, 4, '초밥/회', 'KIND');
INSERT INTO CATEGORY_M VALUES (8, 5, '케이크',  'KIND');
INSERT INTO CATEGORY_M VALUES (9, 5, '쿠키',    'KIND');
INSERT INTO CATEGORY_M VALUES (10, 7, '떡볶이', 'KIND');
COMMIT;
SELECT * FROM CATEGORY_L ORDER BY CATEGORYL_ID;
SELECT * FROM CATEGORY_M ORDER BY CATEGORYM_ID;

DROP TABLE THEME_RECIPE        CASCADE CONSTRAINTS;
DROP TABLE FAVORITE            CASCADE CONSTRAINTS;
DROP TABLE RECIPE_LIKE         CASCADE CONSTRAINTS;
DROP TABLE RECOMMENDED_THEME   CASCADE CONSTRAINTS;
DROP TABLE RECIPE_STEP         CASCADE CONSTRAINTS;
DROP TABLE RECIPE_INGREDIENTS  CASCADE CONSTRAINTS;
DROP TABLE INGREDIENT          CASCADE CONSTRAINTS;
DROP TABLE REVIEW              CASCADE CONSTRAINTS;
DROP TABLE RECIPE              CASCADE CONSTRAINTS;
DROP TABLE CATEGORY_M          CASCADE CONSTRAINTS;
DROP TABLE CATEGORY_L          CASCADE CONSTRAINTS;
DROP TABLE CHEF_INTRO          CASCADE CONSTRAINTS;
DROP TABLE USERS               CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_RECIPE;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_CATEGORY_L;
DROP SEQUENCE SEQ_CATEGORY_M;
DROP SEQUENCE SEQ_INGREDIENT;
DROP SEQUENCE SEQ_RECIPE_INGR;
DROP SEQUENCE SEQ_RECIPE_STEP;
DROP SEQUENCE SEQ_THEME;
DROP SEQUENCE SEQ_FAVORITE;
DROP SEQUENCE SEQ_THEME_RECIPE;
DROP SEQUENCE RECOMMENDED_THEME_SEQ;
COMMIT;
CREATE TABLE USERS (USER_ID VARCHAR2(20), EMAIL VARCHAR2(200) NOT NULL, PASSWORD VARCHAR2(255) NOT NULL, NICKNAME VARCHAR2(30) NOT NULL, PHONE VARCHAR2(20), PROFILE_IMG VARCHAR2(500), BIRTHDAY DATE, IS_DELETED NUMBER(1,0) DEFAULT 0 NOT NULL, MEDAL_GRADE VARCHAR2(10), PRIMARY KEY (USER_ID), UNIQUE (EMAIL), UNIQUE (NICKNAME));
CREATE TABLE CATEGORY_L (CATEGORYL_ID NUMBER(11,0), NAME VARCHAR2(50) NOT NULL, TYPE VARCHAR2(20) NOT NULL, PRIMARY KEY (CATEGORYL_ID));
CREATE TABLE CATEGORY_M (CATEGORYM_ID NUMBER(11,0), CATEGORYL_ID NUMBER(11,0) NOT NULL, NAME VARCHAR2(50) NOT NULL, TYPE VARCHAR2(20) NOT NULL, PRIMARY KEY (CATEGORYM_ID), CONSTRAINT FK_CATM_CATL FOREIGN KEY (CATEGORYL_ID) REFERENCES CATEGORY_L (CATEGORYL_ID));
CREATE TABLE RECIPE (RECIPE_ID NUMBER(20,0), USER_ID VARCHAR2(20) NOT NULL, CATEGORY_ID NUMBER(11,0) NOT NULL, TITLE VARCHAR2(200) NOT NULL, THUMBNAIL VARCHAR2(500), DESCRIPTION CLOB, SERVINGS NUMBER(5,0) NOT NULL, COOK_TIME NUMBER(5,0) NOT NULL, DIFFICULTY NUMBER(1,0) NOT NULL, VIEW_COUNT NUMBER(11,0) DEFAULT 0 NOT NULL, AVG_RATING NUMBER(3,1), IS_DELETED NUMBER(1,0) DEFAULT 0 NOT NULL, CREATED_AT DATE DEFAULT SYSDATE NOT NULL, LINK VARCHAR2(500), CONSTRAINT CK_RECIPE_DIFF CHECK (DIFFICULTY IN (1,2,3)), PRIMARY KEY (RECIPE_ID), CONSTRAINT FK_RECIPE_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID), CONSTRAINT FK_RECIPE_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY_M (CATEGORYM_ID));
CREATE TABLE REVIEW (REVIEW_ID NUMBER(20,0), USER_ID VARCHAR2(20) NOT NULL, RECIPE_ID NUMBER(20,0) NOT NULL, RATING NUMBER(3,1), CONTENT CLOB, PARENT_REVIEW_ID NUMBER(20,0), IS_DELETED NUMBER(1,0) DEFAULT 0 NOT NULL, CREATED_AT DATE DEFAULT SYSDATE NOT NULL, CONSTRAINT CK_REVIEW_RATING CHECK (RATING IS NULL OR (RATING BETWEEN 1.0 AND 5.0)), PRIMARY KEY (REVIEW_ID), CONSTRAINT FK_REVIEW_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID), CONSTRAINT FK_REVIEW_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (RECIPE_ID), CONSTRAINT FK_REVIEW_PARENT FOREIGN KEY (PARENT_REVIEW_ID) REFERENCES REVIEW (REVIEW_ID));
CREATE TABLE INGREDIENT (INGREDIENT_ID NUMBER(11,0), NAME VARCHAR2(100) NOT NULL, UNIT VARCHAR2(20), PRIMARY KEY (INGREDIENT_ID));
CREATE TABLE RECIPE_INGREDIENTS (RECIPE_INGR_ID NUMBER(20,0), INGREDIENT_ID NUMBER(11,0) NOT NULL, RECIPE_ID NUMBER(20,0) NOT NULL, AMOUNT VARCHAR2(50) NOT NULL, PRIMARY KEY (RECIPE_INGR_ID), CONSTRAINT FK_RI_INGREDIENT FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT (INGREDIENT_ID), CONSTRAINT FK_RI_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (RECIPE_ID) ON DELETE CASCADE);
CREATE TABLE RECIPE_STEP (STEP_ID NUMBER(20,0), RECIPE_ID NUMBER(20,0) NOT NULL, STEP_NO NUMBER(5,0) NOT NULL, IMAGE_URL VARCHAR2(500), CONTENT CLOB NOT NULL, PRIMARY KEY (STEP_ID), CONSTRAINT FK_STEP_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (RECIPE_ID) ON DELETE CASCADE);
CREATE TABLE RECOMMENDED_THEME (THEME_ID NUMBER(11,0), USER_ID VARCHAR2(20) NOT NULL, TITLE VARCHAR2(100) NOT NULL, DESCRIPTION CLOB, THUMBNAIL VARCHAR2(500), LINK_URL VARCHAR2(500), IS_VISIBLE NUMBER(1,0) DEFAULT 1 NOT NULL, VIEW_COUNT NUMBER(11,0) DEFAULT 0 NOT NULL, CREATED_AT DATE DEFAULT SYSDATE NOT NULL, SUBTITLE VARCHAR2(200), PRIMARY KEY (THEME_ID), CONSTRAINT FK_THEME_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID));
CREATE TABLE RECIPE_LIKE (RECIPE_ID NUMBER(20,0) NOT NULL, USER_ID VARCHAR2(20) NOT NULL, CREATED_AT DATE DEFAULT SYSDATE NOT NULL, PRIMARY KEY (RECIPE_ID, USER_ID), CONSTRAINT FK_LIKE_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (RECIPE_ID), CONSTRAINT FK_LIKE_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID));
CREATE TABLE FAVORITE (FAVORITE_ID NUMBER(20,0), USER_ID VARCHAR2(20) NOT NULL, RECIPE_ID NUMBER(20,0) NOT NULL, CREATED_AT DATE DEFAULT SYSDATE NOT NULL, PRIMARY KEY (FAVORITE_ID), CONSTRAINT UQ_FAVORITE UNIQUE (USER_ID, RECIPE_ID), CONSTRAINT FK_FAV_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID), CONSTRAINT FK_FAV_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (RECIPE_ID));
CREATE TABLE THEME_RECIPE (THEME_RECIPE_ID NUMBER(20,0), THEME_ID NUMBER(11,0) NOT NULL, RECIPE_ID NUMBER(20,0) NOT NULL, SORT_ORDER NUMBER(5,0), USER_ID VARCHAR2(20), DESCRIPTION VARCHAR2(1000), PRIMARY KEY (THEME_RECIPE_ID), CONSTRAINT UQ_THEME_RECIPE UNIQUE (THEME_ID, RECIPE_ID), CONSTRAINT FK_TR_THEME FOREIGN KEY (THEME_ID) REFERENCES RECOMMENDED_THEME (THEME_ID) ON DELETE CASCADE, CONSTRAINT FK_TR_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (RECIPE_ID));
CREATE TABLE CHEF_INTRO (USER_ID VARCHAR2(50) NOT NULL, INTRO VARCHAR2(1000), UPDATED_AT DATE DEFAULT SYSDATE NOT NULL, CONSTRAINT PK_CHEF_INTRO PRIMARY KEY (USER_ID), CONSTRAINT FK_CHEF_INTRO_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID));
CREATE SEQUENCE SEQ_CATEGORY_L  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_M  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECIPE      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INGREDIENT  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECIPE_INGR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECIPE_STEP START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_THEME       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FAVORITE    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_THEME_RECIPE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE RECOMMENDED_THEME_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_RECIPE_USER     ON RECIPE (USER_ID);
CREATE INDEX IDX_RECIPE_CATEGORY ON RECIPE (CATEGORY_ID);
CREATE INDEX IDX_RECIPE_CREATED  ON RECIPE (CREATED_AT DESC);
CREATE INDEX IDX_RECIPE_VIEWCNT  ON RECIPE (VIEW_COUNT DESC);
CREATE INDEX IDX_RECIPE_RATING   ON RECIPE (AVG_RATING DESC);
CREATE INDEX IDX_REVIEW_RECIPE   ON REVIEW (RECIPE_ID);
CREATE INDEX IDX_REVIEW_PARENT   ON REVIEW (PARENT_REVIEW_ID);
CREATE INDEX IDX_FAVORITE_USER   ON FAVORITE (USER_ID);
CREATE INDEX IDX_THEME_VISIBLE   ON RECOMMENDED_THEME (IS_VISIBLE, CREATED_AT DESC);
INSERT INTO USERS VALUES ('admin','admin@bggchef.com','admin1234','관리자','010-0000-0000',NULL,NULL,0,'골드');
INSERT INTO CATEGORY_L VALUES (1,'한식','CULTURE');
INSERT INTO CATEGORY_L VALUES (2,'양식','CULTURE');
INSERT INTO CATEGORY_L VALUES (3,'중식','CULTURE');
INSERT INTO CATEGORY_L VALUES (4,'일식','CULTURE');
INSERT INTO CATEGORY_L VALUES (5,'디저트','KIND');
INSERT INTO CATEGORY_L VALUES (6,'음료','KIND');
INSERT INTO CATEGORY_L VALUES (7,'분식','KIND');
INSERT INTO CATEGORY_M VALUES (1,1,'찌개/국','KIND');
INSERT INTO CATEGORY_M VALUES (2,1,'구이','KIND');
INSERT INTO CATEGORY_M VALUES (3,1,'볶음','KIND');
INSERT INTO CATEGORY_M VALUES (4,2,'파스타','KIND');
INSERT INTO CATEGORY_M VALUES (5,2,'스테이크','KIND');
INSERT INTO CATEGORY_M VALUES (6,3,'면류','KIND');
INSERT INTO CATEGORY_M VALUES (7,4,'초밥/회','KIND');
INSERT INTO CATEGORY_M VALUES (8,5,'케이크','KIND');
INSERT INTO CATEGORY_M VALUES (9,5,'쿠키','KIND');
INSERT INTO CATEGORY_M VALUES (10,7,'떡볶이','KIND');
COMMIT;
SELECT * FROM CATEGORY_L ORDER BY CATEGORYL_ID;
SELECT * FROM CATEGORY_M ORDER BY CATEGORYM_ID;