-- ========== TABLES (컬럼 + 제약조건 포함) ==========

  CREATE TABLE "BGGCHEF"."CATEGORY_L"
   (	"CATEGORYL_ID" NUMBER(11,0),
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"TYPE" VARCHAR2(20) NOT NULL ENABLE,
	 PRIMARY KEY ("CATEGORYL_ID") ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."CATEGORY_M"
   (	"CATEGORYM_ID" NUMBER(11,0),
	"CATEGORYL_ID" NUMBER(11,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"TYPE" VARCHAR2(20) NOT NULL ENABLE,
	 PRIMARY KEY ("CATEGORYM_ID") ENABLE,
	 CONSTRAINT "FK_CATM_CATL" FOREIGN KEY ("CATEGORYL_ID")
	  REFERENCES "BGGCHEF"."CATEGORY_L" ("CATEGORYL_ID") ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."CHEF_INTRO"
   (	"USER_ID" VARCHAR2(50) NOT NULL ENABLE,
	"INTRO" VARCHAR2(1000),
	"UPDATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "PK_CHEF_INTRO" PRIMARY KEY ("USER_ID") ENABLE,
	 CONSTRAINT "FK_CHEF_INTRO_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "BGGCHEF"."USERS" ("USER_ID") ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."FAVORITE"
   (	"FAVORITE_ID" NUMBER(20,0),
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"RECIPE_ID" NUMBER(20,0) NOT NULL ENABLE,
	"CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 PRIMARY KEY ("FAVORITE_ID") ENABLE,
	 CONSTRAINT "UQ_FAVORITE" UNIQUE ("USER_ID", "RECIPE_ID") ENABLE,
	 CONSTRAINT "FK_FAV_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "BGGCHEF"."USERS" ("USER_ID") ENABLE,
	 CONSTRAINT "FK_FAV_RECIPE" FOREIGN KEY ("RECIPE_ID")
	  REFERENCES "BGGCHEF"."RECIPE" ("RECIPE_ID") ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."INGREDIENT"
   (	"INGREDIENT_ID" NUMBER(11,0),
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"UNIT" VARCHAR2(20),
	 PRIMARY KEY ("INGREDIENT_ID") ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."RECIPE"
   (	"RECIPE_ID" NUMBER(20,0),
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"CATEGORY_ID" NUMBER(11,0) NOT NULL ENABLE,
	"TITLE" VARCHAR2(200) NOT NULL ENABLE,
	"THUMBNAIL" VARCHAR2(500),
	"DESCRIPTION" CLOB,
	"SERVINGS" NUMBER(5,0) NOT NULL ENABLE,
	"COOK_TIME" NUMBER(5,0) NOT NULL ENABLE,
	"DIFFICULTY" NUMBER(1,0) NOT NULL ENABLE,
	"VIEW_COUNT" NUMBER(11,0) DEFAULT 0 NOT NULL ENABLE,
	"AVG_RATING" NUMBER(3,1),
	"IS_DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"LINK" VARCHAR2(500),
	 CONSTRAINT "CK_RECIPE_DIFF" CHECK (difficulty IN (1, 2, 3)) ENABLE,
	 PRIMARY KEY ("RECIPE_ID") ENABLE,
	 CONSTRAINT "FK_RECIPE_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "BGGCHEF"."USERS" ("USER_ID") ENABLE,
	 CONSTRAINT "FK_RECIPE_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "BGGCHEF"."CATEGORY_M" ("CATEGORYM_ID") ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."RECIPE_INGREDIENTS"
   (	"RECIPE_INGR_ID" NUMBER(20,0),
	"INGREDIENT_ID" NUMBER(11,0) NOT NULL ENABLE,
	"RECIPE_ID" NUMBER(20,0) NOT NULL ENABLE,
	"AMOUNT" VARCHAR2(50) NOT NULL ENABLE,
	 PRIMARY KEY ("RECIPE_INGR_ID") ENABLE,
	 CONSTRAINT "FK_RI_INGREDIENT" FOREIGN KEY ("INGREDIENT_ID")
	  REFERENCES "BGGCHEF"."INGREDIENT" ("INGREDIENT_ID") ENABLE,
	 CONSTRAINT "FK_RI_RECIPE" FOREIGN KEY ("RECIPE_ID")
	  REFERENCES "BGGCHEF"."RECIPE" ("RECIPE_ID") ON DELETE CASCADE ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."RECIPE_LIKE"
   (	"RECIPE_ID" NUMBER(20,0) NOT NULL ENABLE,
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 PRIMARY KEY ("RECIPE_ID", "USER_ID") ENABLE,
	 CONSTRAINT "FK_LIKE_RECIPE" FOREIGN KEY ("RECIPE_ID")
	  REFERENCES "BGGCHEF"."RECIPE" ("RECIPE_ID") ENABLE,
	 CONSTRAINT "FK_LIKE_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "BGGCHEF"."USERS" ("USER_ID") ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."RECIPE_STEP"
   (	"STEP_ID" NUMBER(20,0),
	"RECIPE_ID" NUMBER(20,0) NOT NULL ENABLE,
	"STEP_NO" NUMBER(5,0) NOT NULL ENABLE,
	"IMAGE_URL" VARCHAR2(500),
	"CONTENT" CLOB NOT NULL ENABLE,
	 PRIMARY KEY ("STEP_ID") ENABLE,
	 CONSTRAINT "FK_STEP_RECIPE" FOREIGN KEY ("RECIPE_ID")
	  REFERENCES "BGGCHEF"."RECIPE" ("RECIPE_ID") ON DELETE CASCADE ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."RECOMMENDED_THEME"
   (	"THEME_ID" NUMBER(11,0),
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"TITLE" VARCHAR2(100) NOT NULL ENABLE,
	"DESCRIPTION" CLOB,
	"THUMBNAIL" VARCHAR2(500),
	"LINK_URL" VARCHAR2(500),
	"IS_VISIBLE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"VIEW_COUNT" NUMBER(11,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SUBTITLE" VARCHAR2(200),
	 PRIMARY KEY ("THEME_ID") ENABLE,
	 CONSTRAINT "FK_THEME_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "BGGCHEF"."USERS" ("USER_ID") ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."REVIEW"
   (	"REVIEW_ID" NUMBER(20,0),
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"RECIPE_ID" NUMBER(20,0),
	"RATING" NUMBER(3,1),
	"CONTENT" CLOB,
	"PARENT_REVIEW_ID" NUMBER(20,0),
	"IS_DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"THEME_ID" NUMBER(11,0),
	 CONSTRAINT "CK_REVIEW_RATING" CHECK (rating IS NULL OR (rating BETWEEN 1.0 AND 5.0)) ENABLE,
	 PRIMARY KEY ("REVIEW_ID") ENABLE,
	 CONSTRAINT "FK_REVIEW_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "BGGCHEF"."USERS" ("USER_ID") ENABLE,
	 CONSTRAINT "FK_REVIEW_RECIPE" FOREIGN KEY ("RECIPE_ID")
	  REFERENCES "BGGCHEF"."RECIPE" ("RECIPE_ID") ENABLE,
	 CONSTRAINT "FK_REVIEW_PARENT" FOREIGN KEY ("PARENT_REVIEW_ID")
	  REFERENCES "BGGCHEF"."REVIEW" ("REVIEW_ID") ENABLE,
	 CONSTRAINT "FK_REVIEW_THEME" FOREIGN KEY ("THEME_ID")
	  REFERENCES "BGGCHEF"."RECOMMENDED_THEME" ("THEME_ID") ON DELETE CASCADE ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."THEME_RECIPE"
   (	"THEME_RECIPE_ID" NUMBER(20,0),
	"THEME_ID" NUMBER(11,0) NOT NULL ENABLE,
	"RECIPE_ID" NUMBER(20,0) NOT NULL ENABLE,
	"SORT_ORDER" NUMBER(5,0),
	"USER_ID" VARCHAR2(20),
	"DESCRIPTION" VARCHAR2(1000),
	"RECIPE_IMAGE" VARCHAR2(255),
	"THUMBNAIL" VARCHAR2(500),
	 PRIMARY KEY ("THEME_RECIPE_ID") ENABLE,
	 CONSTRAINT "UQ_THEME_RECIPE" UNIQUE ("THEME_ID", "RECIPE_ID") ENABLE,
	 CONSTRAINT "FK_TR_THEME" FOREIGN KEY ("THEME_ID")
	  REFERENCES "BGGCHEF"."RECOMMENDED_THEME" ("THEME_ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "FK_TR_RECIPE" FOREIGN KEY ("RECIPE_ID")
	  REFERENCES "BGGCHEF"."RECIPE" ("RECIPE_ID") ENABLE
   ) ;



  CREATE TABLE "BGGCHEF"."USERS"
   (	"USER_ID" VARCHAR2(20),
	"EMAIL" VARCHAR2(200) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(255) NOT NULL ENABLE,
	"NICKNAME" VARCHAR2(30) NOT NULL ENABLE,
	"PHONE" VARCHAR2(20),
	"PROFILE_IMG" VARCHAR2(500),
	"BIRTHDAY" DATE,
	"IS_DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"MEDAL_GRADE" VARCHAR2(30),
	 PRIMARY KEY ("USER_ID") ENABLE,
	 UNIQUE ("EMAIL") ENABLE,
	 UNIQUE ("NICKNAME") ENABLE
   ) ;


-- ========== INDEXES ==========

  CREATE INDEX "BGGCHEF"."IDX_FAVORITE_USER" ON "BGGCHEF"."FAVORITE" ("USER_ID")
  ;



  CREATE INDEX "BGGCHEF"."IDX_RECIPE_CATEGORY" ON "BGGCHEF"."RECIPE" ("CATEGORY_ID")
  ;



  CREATE INDEX "BGGCHEF"."IDX_RECIPE_CREATED" ON "BGGCHEF"."RECIPE" ("CREATED_AT" DESC)
  ;



  CREATE INDEX "BGGCHEF"."IDX_RECIPE_RATING" ON "BGGCHEF"."RECIPE" ("AVG_RATING" DESC)
  ;



  CREATE INDEX "BGGCHEF"."IDX_RECIPE_USER" ON "BGGCHEF"."RECIPE" ("USER_ID")
  ;



  CREATE INDEX "BGGCHEF"."IDX_RECIPE_VIEWCNT" ON "BGGCHEF"."RECIPE" ("VIEW_COUNT" DESC)
  ;



  CREATE INDEX "BGGCHEF"."IDX_REVIEW_PARENT" ON "BGGCHEF"."REVIEW" ("PARENT_REVIEW_ID")
  ;



  CREATE INDEX "BGGCHEF"."IDX_REVIEW_RECIPE" ON "BGGCHEF"."REVIEW" ("RECIPE_ID")
  ;



  CREATE INDEX "BGGCHEF"."IDX_THEME_VISIBLE" ON "BGGCHEF"."RECOMMENDED_THEME" ("IS_VISIBLE", "CREATED_AT" DESC)
  ;



  CREATE UNIQUE INDEX "BGGCHEF"."PK_CHEF_INTRO" ON "BGGCHEF"."CHEF_INTRO" ("USER_ID")
  ;



  CREATE UNIQUE INDEX "BGGCHEF"."UQ_FAVORITE" ON "BGGCHEF"."FAVORITE" ("USER_ID", "RECIPE_ID")
  ;



  CREATE UNIQUE INDEX "BGGCHEF"."UQ_THEME_RECIPE" ON "BGGCHEF"."THEME_RECIPE" ("THEME_ID", "RECIPE_ID")
  ;


-- ========== SEQUENCES ==========

   CREATE SEQUENCE  "BGGCHEF"."RECOMMENDED_THEME_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."REVIEW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 486 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."SEQ_CATEGORY_L"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."SEQ_CATEGORY_M"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."SEQ_FAVORITE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."SEQ_INGREDIENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 29 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."SEQ_RECIPE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."SEQ_RECIPE_INGR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 69 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."SEQ_RECIPE_STEP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 32 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."SEQ_REVIEW"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 38 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."SEQ_THEME"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "BGGCHEF"."SEQ_THEME_RECIPE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 36 NOCACHE  NOORDER  NOCYCLE ;


-- ========== VIEWS ==========
